# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

version = `motion --version`; puts "RubyMotion version #{version}"; puts " "

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'LRM-Table'
  app.sdk_version = "8.0"
  app.deployment_target = "7.1"
end
