source 'https://rubygems.org'

gem 'rake', '10.4.2'

gem 'ruby_motion_query', '1.3.5'
gem 'bubble-wrap', '1.8.0'
gem 'motion-cocoapods', '1.7.1'
gem 'cocoapods','0.37.1'

# Pretty printing
#gem 'motion_print' 

# ProMotion is a screen system. It works well with RMQ and is a nice wrapper around controllers 
# I would still use RMQ's stylesheets with ProMotion (not theirs), however
#gem 'ProMotion', '~> 1.2.0' 

# For beta distribution a exception reporting
#gem 'motion-hockeyapp' 

# If you're using Core Data, this is recommended
#gem 'cdq' 

# If you need to access the network, use AFMotion; it uses AFNetworking
#gem 'afmotion' 


